name: centos
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  centos:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
    - name: install deps
      run: |
        yum install -y gcc gmp gmp-devel make ncurses ncurses-compat-libs ncurses-devel xz perl
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 BOOTSTRAP_HASKELL_GHC_VERSION=8.10.7 sh
    - uses: actions/checkout@v3
    - name: Test
      run: |
        source ~/.ghcup/env
        cabal update
        cabal test --test-show-details=direct
