name: FreeBSD CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  freebsd:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [self-hosted, FreeBSD, X64]
            ghc: 9.4.8
          - os: [self-hosted, FreeBSD, X64]
            ghc: 9.6.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: |
          pkg install -y curl gcc gmp gmake ncurses perl5 libffi libiconv git bash misc/compat10x misc/compat11x misc/compat12x gmake llvm14 bzip2
          export RUNNER_OS=FreeBSD
          export GHCUP_INSTALL_BASE_PREFIX="$GITHUB_WORKSPACE"
          export GHCUP_BIN="$GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin"
          export PATH="$GHCUP_BIN:$HOME/.local/bin:$PATH"
          export CABAL_DIR="$GITHUB_WORKSPACE/cabal"
          export TAR_TEST_FILE="${CABAL_DIR}/packages/hackage.haskell.org/01-index.tar"
          export TMPDIR="${GITHUB_WORKSPACE}/tmp"
          export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
          export BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1
          export BOOTSTRAP_HASKELL_GHC_VERSION=${{ matrix.ghc }}
          export BOOTSTRAP_HASKELL_ADJUST_BASHRC=yes
          mkdir -p "${TMPDIR}"
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
          cabal test all
          cabal bench all
          bash htar/test-large-files.sh

